name: Synk Test

on:
  push:
    branches:
      - main

jobs:
  synk_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Synk CLI
        run: |
          curl https://downloads.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          sudo mv ./snyk /usr/local/bin/snyk

      - name: Test with Synk
        run: snyk test --file=pom.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
