name: run shell commands

on: [push]

jobs:
  Snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Echo string
        run: echo "Running Snyk"
      - name: Checkout code
        uses: actions/checkout@v2     
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}