name: Java Github actions

on:
  push:
    branches:
      - main

jobs:
  Java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install Synk CLI
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Run Synk test
        run: synk test --file=pom.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}