name: run shell commands

on:
  push:
    branches:
      - main

jobs:
  Snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Install Synk CLI
        run: curl -sSL https://get.synk.io/cli | sh  
      - name: Run Synk test
        run: synk test --file=pom.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}