name: Java
on: push
jobs:
  Java-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@master

      - name: List code
        run: ls -lrt

      - name: Run Snyk to check for vulnerabilities
        uses:  snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}