name: Java
on: push
jobs:
  Java-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@master

      - name: Change directory
        run: cd Java && ls -lrt
        

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}