name: Java CI

env:
  APPLICATION_NAME: "Sample-java-Application"
  JfrogHelmRepo: "devsecops-guild-cloud-agonistic-helm-local"
  JfrogDockerRepo: "devsecops-guild-cloud-agonistic-docker-local"
  JfrogURL: "kyndryl.jfrog.io"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JfrogGoRepo=: "devsecops-guild-cloud-agonistic-go-local"
  JFrogArtifactory: "https://kyndryl.jfrog.io/artifactory/"
  applicatonName: "sales-order-golang"


on: push

jobs:
  Java-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@master

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion 
        uses: gittools/actions/gitversion/execute@v0

      - name: Git-Secret Validation
        run: |
          sudo apt-get update && sudo apt-get -y install git-secrets
          echo "Security check started before build"
          echo "Checking for any secrets stored in the repo using git-secrets"
          if ! git-secrets --scan -r $PWD; then
              echo "CI Job Aborting as there is Secret Stored in the Repository."
              exit 1
          else 
              echo "No Secret found in the code" 
              echo "Proceed for next step....."                            
          fi

      - name: Directory For Jfrog Artifactory
        env:
          VERSION: ${{ steps.gitversion.outputs.fullSemVer }}
        run: |
          mkdir $VERSION
          mkdir -p $VERSION/Build-artifacts
          mkdir -p $VERSION/Build-reports
          mkdir -p $VERSION/Build-configuration

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: cd Java && mvn clean package

      - name : Jfrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JFrogArtifactory }}
          JF_USER: ${{ secrets.JfrogUser }}
          JF_PASSWORD: ${{ secrets.JfrogUserAPIKey }}
          JF_SERVER_ID : "SERVER"
      - run: |
           jf rt ping

      - name: Upload to JFrog Artifactory
        run: |
          jf rt upload --recursive=true --flat=false --url ${{ secrets.JFrogArtifactory }} $VERSION/ ${{ env.JfrogGoRepo }}/${{ env.applicatonName }}/


      # - name: Install Snyk CLI
      #   run: |     
      #     curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      #     sudo apt-get install -y nodejs
      #     sudo npm install -g snyk  

      # - name: Run Snyk test
      #   run: |
      #     cd Java
      #     chmod +x mvnw
      #     ./mvnw dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-graph.dot
      #     snyk test --file=pom.xml     
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      #- name: Push Aqua scan results to DI Accelerator
        # if: success()
        # env:
        #   VERSION: ${{ steps.gitversion.outputs.fullSemVer }}
        # run: |
        #   cd Java
        #   curl -X POST \
        #     -H "Authorization: Token ${{ secrets.DI_TOKEN }}" \
        #     -H "Content-Type: application/json" \
        #     -d "@aqua-results.json" \
        #     "https://di-accelerator.kyndryl-cloud.com/dash/api/dev_secops/v3/technical-services/image-scan/aqua/vulnerabilities?technicalServiceName=$APPLICATION_NAME:$VERSION"