name: Java
on: push
jobs:
  Java-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@master

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package