name: Java
on: push
jobs:
  Java-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@master

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: cd Java && mvn clean package

      - name: Push Trivy scan results to DI Accelerator
        if: success()
        env:
          APPLICATION_NAME: Sample-java
          VERSION: 1.0.0
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.DI_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "@aqua-results.json" \
            "https://di-accelerator.kyndryl-cloud.com/dash/api/dev_secops/v3/technical-services/image-scan/aqua/vulnerabilities?technicalServiceName=$applicatonName:$version"